# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2

# Mod Properties
mod_version=1.1.2
maven_group=me.drex.votelistener
archives_base_name=votelistener


# Dependencies
fabric_version=0.149.0+26.1.2
nuvotifier_version=2.7.2
nuvotifier_fabric_version=1.1.0+26.1-rc-3
placeholder_api_version=3.0.0+26.1
fabric_permission_api_version=0.7.0
vanish_version=1.6.8+26.1
